# Generated by Django 4.2.1 on 2023-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0002_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
