# Generated by Django 4.2.1 on 2023-07-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0004_cakes_cakeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='username',
        ),
    ]
