# Generated by Django 4.2.1 on 2023-07-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0005_rename_user_name_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=150)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakestoreapp.customer')),
            ],
        ),
    ]
