# Generated by Django 4.2.1 on 2023-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0006_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
