# Generated by Django 4.2.1 on 2023-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0007_alter_feedbacks_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cakeimage', models.ImageField(null=True, upload_to='cakeimgs')),
            ],
        ),
    ]
