# Generated by Django 4.2.1 on 2023-07-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0009_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cakename',
            new_name='customer',
        ),
    ]
