# Generated by Django 4.2.1 on 2023-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0010_rename_cakename_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
