# Generated by Django 4.2.1 on 2023-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0012_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
