# Generated by Django 4.2.1 on 2023-07-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0013_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakes',
            name='category',
        ),
        migrations.AddField(
            model_name='cakes',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakestoreapp.category'),
        ),
    ]
