# Generated by Django 4.2.1 on 2023-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0014_remove_cakes_category_cakes_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
