# Generated by Django 4.2.1 on 2023-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestoreapp', '0015_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cakes',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
